············rightL·=·dfs(node.right)
············leftL·=·dfs(node.left)
········def·dfs(node):
············if·not·node:·return·-1
········maxL·=·0
····def·diameterOfBinaryTree(self,·root:·Optional[TreeNode])·->·int:
#·········self.right·=·right
class·Solution:
#·····def·__init__(self,·val=0,·left=None,·right=None):
#·········self.val·=·val
#·········self.left·=·left
#·class·TreeNode:
#·Definition·for·a·binary·tree·node.
[
